version: '3.8'

services:
  frontend:
    image: suhail12/post_feeds_frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    image: suhail12/post_feeds_backend:latest
    ports:
      - "8080:8080"
